We are an analyst for a sports talent agency. The firm is dedicated to providing athletes machine learning and predictive modeling. Bring in the historic data requested by different teams, save them as a pandas Dataframe and answer their questions

In [ ]:
import pandas as pd
#load the female olympic swimmer dataset into pandas
#read from the local file
female_swimmers = pd.read_csv('/content/female_olympic_swimmers.csv')
female_swimmers.head()

,Unnamed: 0,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,474,259,Reema Abdo,F,21.0,173.0,59.0,Canada,CAN,1984 Summer,1984,Summer,Los Angeles,Swimming,Swimming Women's 100 metres Backstroke,NaN
1,475,259,Reema Abdo,F,21.0,173.0,59.0,Canada,CAN,1984 Summer,1984,Summer,Los Angeles,Swimming,Swimming Women's 200 metres Backstroke,NaN
2,476,259,Reema Abdo,F,21.0,173.0,59.0,Canada,CAN,1984 Summer,1984,Summer,Los Angeles,Swimming,Swimming Women's 4 x 100 metres Medley Relay,Bronze
3,517,290,Fatima Abdul Majeed Hameed Al-Kirashi,F,14.0,NaN,NaN,Bahrain,BRN,2000 Summer,2000,Summer,Sydney,Swimming,Swimming Women's 50 metres Freestyle,NaN
4,729,417,Sara Helena berg,F,17.0,190.0,73.0,Sweden,SWE,1988 Summer,1988,Summer,Seoul,Swimming,Swimming Women's 50 metres Freestyle,NaN

In [ ]:
#what country produced the most female olympic swimmers from 2000 to 2016?
filter= female_swimmers[(female_swimmers['Year']>=2000) & (female_swimmers['Year']<=2016)]
#group by team, NOC and count
team_counts = female_swimmers.groupby(['Team','NOC']).size()
#sort by team count
most_female_swimmers = team_counts.sort_values(ascending=False)
#find the top country
top_ten_countries = most_female_swimmers.head(10)
print(top_ten_countries)

Team           NOC
United States  USA    730
Great Britain  GBR    593
Australia      AUS    588
Canada         CAN    482
Netherlands    NED    425
Japan          JPN    406
Sweden         SWE    347
France         FRA    344
Germany        GER    324
China          CHN    307
dtype: int64

A competitive swimwear company is launching a swimwear line for taller women. The compnay wants to limit the search to 2016 competitors. Identify the talles medalist from the 2016 games.

In [ ]:
#find tallest medalist from 2016 games
#filter for 2016
year_filter = female_swimmers[female_swimmers['Year'] == 2016]
#drop rows where "Medal" is NaN
female_swimmer_medalist = year_filter.dropna(subset=['Medal'])
#find the tallest swimmer
tallest_swimmer = female_swimmer_medalist.sort_values(by='Height', ascending=False).iloc[0]
print(tallest_swimmer)

Unnamed: 0                                             206160
ID                                                     103490
Name                                             Cierra Runge
Sex                                                         F
Age                                                      20.0
Height                                                  193.0
Weight                                                   85.0
Team                                            United States
NOC                                                       USA
Games                                             2016 Summer
Year                                                     2016
Season                                                 Summer
City                                           Rio de Janeiro
Sport                                                Swimming
Event         Swimming Women's 4 x 200 metres Freestyle Relay
Medal                                                    Gold
Name: 7460, dtype: object

The strategy team is interested in trends among highest paid athletes. The following GitHub repository has a dataset of 100 highest paid athletes. Load the Athletes.csv files from GitHub and answer the following questions

In [ ]:
#load the GitHub repository
url = 'https://raw.githubusercontent.com/ali-ce/datasets/refs/heads/master/Most-paid-athletes/Athletes.csv'
athlete_salaries = pd.read_csv(url)
athlete_salaries.head()

,Rank,Name,Sport,Total Pay,Salary/Winnings,Endorsements,Nation,Gender,Year of birth,Birth Date,Place of Birth,Height (cm),Wikipedia Page,dbpedia Page,Image,Description
0,55,Aaron Rodgers,Football,"$22,000,000","$14,500,000","$7,500,000",United States,Male,1983,2/12/1983,"Chico, California, United States",188,http://en.wikipedia.org/wiki/Aaron_Rodgers,dbpedia.org/resource/Aaron_Rodgers,http://commons.wikimedia.org/wiki/Special:File...,"Aaron Charles Rodgers (born December 2, 1983) ..."
1,95,Adam Scott,Golf,"$17,700,000","$8,700,000","$9,000,000",Australia,Male,1980,16/07/1980,"Adelaide, Australia",183,https://en.wikipedia.org/wiki/Adam_Scott_(golfer),dbpedia.org/resource/Adam_Scott_(golfer),http://commons.wikimedia.org/wiki/Special:File...,Adam Derek Scott (born 16 July 1980) is an Aus...
2,60,Adrian Gonzalez,Baseball,"$21,500,000","$21,100,000","$400,000",United States,Male,1982,8/05/1982,"San Diego, California, United States",188,http://en.wikipedia.org/wiki/Adrian_Gonzalez,dbpedia.org/resource/Adrian_Gonzalez,http://commons.wikimedia.org/wiki/Special:File...,"Adrian Gonzalez (born May 8, 1982), also known..."
3,48,Alex Rodriguez,Baseball,"$22,900,000","$22,600,000","$300,000",United States,Male,1975,27/07/1975,New York City,190,http://en.wikipedia.org/wiki/Alex_Rodriguez,dbpedia.org/resource/Alex_Rodriguez,http://commons.wikimedia.org/wiki/Special:File...,"Alexander Emmanuel "" Alex "" Rodriguez (born Ju..."
4,93,Alfonso Soriano,Baseball,"$18,050,000","$18,000,000","$50,000",Dominican Republic,Male,1976,7/01/1976,"San Pedro de Macorís, Dominican Republic",185,http://en.wikipedia.org/wiki/Alfonso_Soriano,dbpedia.org/resource/Alfonso_Soriano,http://commons.wikimedia.org/wiki/Special:File...,"Alfonso Guilleard Soriano (born January 7, 197..."

In [ ]:
athlete_salaries['Total Pay'] = athlete_salaries['Total Pay'].str.replace('$', '')

athlete_salaries['Total Pay'] = athlete_salaries['Total Pay'].str.replace(',', '')
#convert to numeric
athlete_salaries['Total Pay'] = pd.to_numeric(athlete_salaries['Total Pay'])
athlete_salaries.head()

,Rank,Name,Sport,Total Pay,Salary/Winnings,Endorsements,Nation,Gender,Year of birth,Birth Date,Place of Birth,Height (cm),Wikipedia Page,dbpedia Page,Image,Description
0,55,Aaron Rodgers,Football,22000000,"$14,500,000","$7,500,000",United States,Male,1983,2/12/1983,"Chico, California, United States",188,http://en.wikipedia.org/wiki/Aaron_Rodgers,dbpedia.org/resource/Aaron_Rodgers,http://commons.wikimedia.org/wiki/Special:File...,"Aaron Charles Rodgers (born December 2, 1983) ..."
1,95,Adam Scott,Golf,17700000,"$8,700,000","$9,000,000",Australia,Male,1980,16/07/1980,"Adelaide, Australia",183,https://en.wikipedia.org/wiki/Adam_Scott_(golfer),dbpedia.org/resource/Adam_Scott_(golfer),http://commons.wikimedia.org/wiki/Special:File...,Adam Derek Scott (born 16 July 1980) is an Aus...
2,60,Adrian Gonzalez,Baseball,21500000,"$21,100,000","$400,000",United States,Male,1982,8/05/1982,"San Diego, California, United States",188,http://en.wikipedia.org/wiki/Adrian_Gonzalez,dbpedia.org/resource/Adrian_Gonzalez,http://commons.wikimedia.org/wiki/Special:File...,"Adrian Gonzalez (born May 8, 1982), also known..."
3,48,Alex Rodriguez,Baseball,22900000,"$22,600,000","$300,000",United States,Male,1975,27/07/1975,New York City,190,http://en.wikipedia.org/wiki/Alex_Rodriguez,dbpedia.org/resource/Alex_Rodriguez,http://commons.wikimedia.org/wiki/Special:File...,"Alexander Emmanuel "" Alex "" Rodriguez (born Ju..."
4,93,Alfonso Soriano,Baseball,18050000,"$18,000,000","$50,000",Dominican Republic,Male,1976,7/01/1976,"San Pedro de Macorís, Dominican Republic",185,http://en.wikipedia.org/wiki/Alfonso_Soriano,dbpedia.org/resource/Alfonso_Soriano,http://commons.wikimedia.org/wiki/Special:File...,"Alfonso Guilleard Soriano (born January 7, 197..."

In [ ]:
# what is the correlation between an athlete's height and total pay
correlation = athlete_salaries['Height (cm)'].corr(athlete_salaries['Total Pay'])
print(correlation)

-0.11495557823126357

In [ ]:
#what is the difference between 75th percentile and 25th percentile of top-paid athlete ages
#calculate age. We only have date of birth so take a reference year and subtract last 4 digits of birth date
ref_year = 2025
athlete_salaries['Age'] = ref_year - athlete_salaries['Birth Date'].str[-4:].astype(int)
#calculate quanitles
iq3 = athlete_salaries['Age'].quantile(.75)
iq1 = athlete_salaries['Age'].quantile(.25)
#calculate iqr
iqr = (iq3-iq1)
print(f"The Interquartile range of ages is: {iqr}")

The Interquartile range of ages is: 5.25

In [ ]:
#compare the mean total pay by sport
sport = athlete_salaries.groupby('Sport')
#calculate mean and sort
mean_salary = sport['Total Pay'].mean()
salary_sort = mean_salary.sort_values(ascending=False)
#print and divide to convert to millions
print(f"The mean salary by sport in millions ($) {salary_sort/1000000}")

The mean salary by sport in millions ($) Sport
Boxing        48.950000
Golf          35.520000
Tennis        33.966667
Soccer        31.500000
Cricket       30.000000
Basketball    29.272222
Racing        25.016667
Track         23.200000
Football      22.690294
Baseball      21.694444
Name: Total Pay, dtype: float64

The basketball team has an API that will return statistics by season. Use the API to call data from the 2024 season to help the team with contract negotiations.

In [ ]:
import requests
import json
basketball_url = 'https://api.server.nbaapi.com/api/playertotals?season=2024&page=1&pageSize=1000'
#get data from the api
response = requests.get(basketball_url)
bball_data = response.json()
bball_df = pd.DataFrame(bball_data['data'])

bball_df.head()

,ID,id,playerId,playerName,position,age,games,gamesStarted,minutesPg,fieldGoals,...,blocks,turnovers,personalFouls,points,team,season,isPlayoff,CreatedAt,UpdatedAt,DeletedAt
0,899,1,doncilu01,Luka Dončić,PG,24,70,70,2624,804,...,38,282,149,2370,DAL,2024,False,2025-06-20T01:05:04.703201Z,2025-06-20T01:05:04.703201Z,None
1,900,2,gilgesh01,Shai Gilgeous-Alexander,PG,25,75,75,2553,796,...,67,162,184,2254,OKC,2024,False,2025-06-20T01:05:04.844939Z,2025-06-20T01:05:04.844939Z,None
2,901,3,antetgi01,Giannis Antetokounmpo,PF,29,73,73,2567,837,...,79,250,210,2222,MIL,2024,False,2025-06-20T01:05:04.99075Z,2025-06-20T01:05:04.99075Z,None
3,902,4,brunsja01,Jalen Brunson,PG,27,77,77,2726,790,...,13,186,144,2212,NYK,2024,False,2025-06-20T01:05:05.131757Z,2025-06-20T01:05:05.131757Z,None
4,903,5,jokicni01,Nikola Jokić,C,28,79,79,2737,822,...,68,237,194,2085,DEN,2024,False,2025-06-20T01:05:05.269539Z,2025-06-20T01:05:05.269539Z,None

In [ ]:
#what is the maximum number of games started by a pleaser in 2024
games_started = bball_df.sort_values(by = 'gamesStarted', ascending = False)
print(games_started.iloc[0]['gamesStarted'])
#how many players started that number of games?
max_games_count = games_started.iloc[0].count()
print(f"{max_games_count} players started in the maximum number of games in the 2024 season")

82
36 players started in the maximum number of games in the 2024 season

Create two new features: Stocks per game that calculates each player's stocks divided by games played in the 2024 season. "minutes_per_game" that calculates each player's average minutes played in a game. Create a list of 10 underused players with the highest "Stocks per Game".

In [ ]:
#create stocks per game column
bball_df['stocks_per_game'] = (bball_df['steals'] + bball_df['blocks']) / bball_df['games']
#create minute per game column
bball_df['minutes_per_game'] = bball_df['minutesPg'] / bball_df['games']
bball_df.head()

,ID,id,playerId,playerName,position,age,games,gamesStarted,minutesPg,fieldGoals,...,personalFouls,points,team,season,isPlayoff,CreatedAt,UpdatedAt,DeletedAt,stocks_per_game,minutes_per_game
0,899,1,doncilu01,Luka Dončić,PG,24,70,70,2624,804,...,149,2370,DAL,2024,False,2025-06-20T01:05:04.703201Z,2025-06-20T01:05:04.703201Z,None,1.957143,37.485714
1,900,2,gilgesh01,Shai Gilgeous-Alexander,PG,25,75,75,2553,796,...,184,2254,OKC,2024,False,2025-06-20T01:05:04.844939Z,2025-06-20T01:05:04.844939Z,None,2.893333,34.040000
2,901,3,antetgi01,Giannis Antetokounmpo,PF,29,73,73,2567,837,...,210,2222,MIL,2024,False,2025-06-20T01:05:04.99075Z,2025-06-20T01:05:04.99075Z,None,2.273973,35.164384
3,902,4,brunsja01,Jalen Brunson,PG,27,77,77,2726,790,...,144,2212,NYK,2024,False,2025-06-20T01:05:05.131757Z,2025-06-20T01:05:05.131757Z,None,1.077922,35.402597
4,903,5,jokicni01,Nikola Jokić,C,28,79,79,2737,822,...,194,2085,DEN,2024,False,2025-06-20T01:05:05.269539Z,2025-06-20T01:05:05.269539Z,None,2.227848,34.645570

In [ ]:
#create a list of 10 underused players with highest stocks per game.
#filter underused players as less than 25 minutes per game
underused_df=bball_df[bball_df['minutes_per_game'] <25]
stocks_sorted = underused_df.sort_values(by='stocks_per_game', ascending=False)
print(stocks_sorted.head(10))
#locate the player with highest stocks per game
stocks_sorted.iloc[0]['playerName']

       ID   id   playerId          playerName position  age  games  \
140  1053  139  gaffoda01      Daniel Gafford       PF   25     74
224  1153  213  kesslwa01      Walker Kessler        C   22     64
835  1409  390  covinro01    Robert Covington       PF   33      3
322  1055  139  gaffoda01      Daniel Gafford       PF   25     29
304  1233  268  thybuma01    Matisse Thybulle       SF   26     65
688  1513  466  williro04     Robert Williams        C   26      6
839  1251  281  batumni01       Nicolas Batum       PF   35      3
461  1361  358  robinmi01   Mitchell Robinson        C   25     31
579  2744  159  porzikr01  Kristaps Porziņģis        C   28      7
406  1328  335  easonta01          Tari Eason       PF   22     22

     gamesStarted  minutesPg  fieldGoals  ...  personalFouls  points  team  \
140            66       1815         348  ...            227     814   2TM
224            22       1493         229  ...            132     518   UTA
835             3         69           3  ...              7       9   LAC
322            21        623         145  ...             80     324   DAL
304            19       1487         126  ...             93     354   POR
688             0        119          17  ...             17      41   POR
839             0         54           3  ...              5       8   LAC
461            21        768          73  ...             55     173   NYK
579             4        165          28  ...             15      86   BOS
406             0        480          88  ...             51     215   HOU

     season  isPlayoff                    CreatedAt  \
140    2024      False  2025-06-20T01:05:27.046509Z
224    2024      False  2025-06-20T01:05:41.417531Z
835    2024      False  2025-06-20T01:06:18.785546Z
322    2024      False  2025-06-20T01:05:27.335691Z
304    2024      False  2025-06-20T01:05:52.825516Z
688    2024      False  2025-06-20T01:06:34.318715Z
839    2024      False  2025-06-20T01:05:55.407965Z
461    2024      False  2025-06-20T01:06:11.449709Z
579    2024       True  2025-06-20T01:09:40.829057Z
406    2024      False  2025-06-20T01:06:06.591688Z

                       UpdatedAt  DeletedAt  stocks_per_game  minutes_per_game
140  2025-06-20T01:05:27.046509Z       None         2.945946         24.527027
224  2025-06-20T01:05:41.417531Z       None         2.875000         23.328125
835  2025-06-20T01:06:18.785546Z       None         2.666667         23.000000
322  2025-06-20T01:05:27.335691Z       None         2.655172         21.482759
304  2025-06-20T01:05:52.825516Z       None         2.492308         22.876923
688  2025-06-20T01:06:34.318715Z       None         2.333333         19.833333
839  2025-06-20T01:05:55.407965Z       None         2.333333         18.000000
461  2025-06-20T01:06:11.449709Z       None         2.322581         24.774194
579  2025-06-20T01:09:40.829057Z       None         2.285714         23.571429
406  2025-06-20T01:06:06.591688Z       None         2.272727         21.818182

[10 rows x 39 columns]

'Daniel Gafford'

The firm created a new Social Media Team, tasked with studying social media presence of athletes. The following Kaggle dataset reports a variety of measurements of atheltes' social media presence. Call the Kaggle dataset API and save it into a dataframe.

In [ ]:
#call the kaggle API
!pip install kaggle
import os
import zipfile
os.environ['KAGGLE_CONFIG_DIR'] = "/content/kaggle_data"
#os.mkdir('/content/kaggle_data')
#copy kaggle.json to kaggle_data folder
#os.rename('/content/kaggle.json','/content/kaggle_data/kaggle.json')
! kaggle datasets download rishidamarla/2017-espn-athletes-fame-rankings

! unzip 2017-espn-athletes-fame-rankings.zip

social_media_df = pd.read_excel('2017 ESPN World Fame 100.xlsx')
social_media_df.head()

y
Requirement already satisfied: kaggle in /usr/local/lib/python3.11/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.11/dist-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2025.7.14)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.4.2)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from kaggle) (5.29.5)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.11/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.11/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from kaggle) (0.5.1)
Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /content/kaggle_data/kaggle.json'
Dataset URL: https://www.kaggle.com/datasets/rishidamarla/2017-espn-athletes-fame-rankings
License(s): CC0-1.0
2017-espn-athletes-fame-rankings.zip: Skipping, found more recently modified local copy (use --force to force download)
Archive:  2017-espn-athletes-fame-rankings.zip
replace 2017 ESPN World Fame 100.xlsx? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: 2017 ESPN World Fame 100.xlsx

,Rank,PY Rank,Last Name,First Name,Sport,Country,Team,Endorsements,Instgram Followers,Facebook Followers,Twitter Followers,Endorsements.1,Instgram Followers.1,Facebook Followers.1,Twitter Followers.1
0,1,1,Ronaldo,Cristiano,Soccer,Portugal,Real Madrid,32.0,93.0,118.1,50.4,32000000,93000000.0,118100000,50400000.0
1,2,2,James,LeBron,Basketball,USA,Cleveland Cavaliers,55.0,28.5,22.6,34.4,55000000,28500000.0,22600000,34400000.0
2,3,3,Messi,Lionel,Soccer,Argentina,Barcelona,28.0,65.1,86.6,NaN,28000000,65100000.0,86600000,0.0
3,4,5,Federer,Roger,Tennis,Switzerland,NaN,60.0,2.8,14.2,6.7,60000000,2800000.0,14200000,6700000.0
4,5,13,Mickelson,Phil,Golf,USA,NaN,50.0,NaN,NaN,NaN,50000000,0.0,0,0.0

In [ ]:
#what social media presence has the highest correlation with endorsements
correlation_metric = social_media_df[['Endorsements','Instgram Followers','Facebook Followers', 'Twitter Followers']]
correlation_metric.corr()

,Endorsements,Instgram Followers,Facebook Followers,Twitter Followers
Endorsements,1.000000,0.228969,0.226319,0.356796
Instgram Followers,0.228969,1.000000,0.930325,0.668668
Facebook Followers,0.226319,0.930325,1.000000,0.689245
Twitter Followers,0.356796,0.668668,0.689245,1.000000

In [ ]:
#create a feature that represents the sum of followers between all three social media platforms
#create new column totaling all three media platforms
social_media_df['social_media_sum']= social_media_df['Facebook Followers'] + social_media_df['Instgram Followers'] + social_media_df['Twitter Followers']
sport = social_media_df.groupby('Sport')
#calculate mean followers by sport
sport_sum_followers = sport['social_media_sum'].mean()
#sort and print
print(sport_sum_followers.sort_values(ascending=False))

Sport
Soccer             41.509111
Cricket            31.400000
Track and Field    30.000000
Basketball         22.795273
MMA                20.166667
Tennis             12.945200
Boxing              9.745000
Formula One         8.184500
Football            7.822000
NASCAR              4.522500
Gymnastics          4.509000
Golf                3.696429
Swimming            2.798000
Badminton                NaN
Table Tennis             NaN
Name: social_media_sum, dtype: float64

In [ ]:
# what sport has the highest average endorsements
avg_endorsements = sport['Endorsements'].mean()
print(avg_endorsements.sort_values(ascending=False))

Sport
Track and Field    30.000000
Tennis             23.350000
Golf               21.363636
Basketball         18.423077
Football            8.875000
Cricket             8.759750
NASCAR              8.000000
Soccer              7.018333
MMA                 6.666667
Formula One         5.500000
Boxing              2.000000
Swimming            1.150000
Gymnastics          1.075000
Badminton                NaN
Table Tennis             NaN
Name: Endorsements, dtype: float64