You are an analyst for a global infant and maternal health advocacy group called JPG. Josephina, the founder, is preparing a presentation for the UN and has asked you to pull some insights for her from the data.

In [ ]:
import pandas as pd
import numpy as np
#create pandas dataframe through url provided
#Read the CSV file into a pandas dataframe.
url = 'https://raw.githubusercontent.com/katiegaertner/ML-Fundamentals/main/world-health-data-numbers.csv'
df_health = pd.read_csv(url)

In [ ]:
#how many rows are in the DataFrame
df_health.shape
#df_health.head()

(194, 18)

View the first five rows of the DataFrame. There is a column called 'Abbreviations', which holds a unique two-character value for each country. Set 'Abbreviations' as the index. Sort the dataframe by this new index.

In [ ]:
#view first 5 entries
df_health.head(5)
#set abbreviaiton as index
df_health = df_health.set_index('Abbreviation')
#sort index
df_health = df_health.sort_index()

In [ ]:
#What country uses 'DZ' as abbreviation
df_health.loc['DZ']

Country                               Algeria
Pop_Density                              18.0
Land_Area                           2381741.0
Birth_Rate                              24.28
CO2_Emissions                        150006.0
CPI                                    151.36
Fertility_Rate                           3.02
GDP                            169988000000.0
Infant mortality_per_1k                  20.1
Life_Expectancy                          76.7
Maternal_Mortality_per_100k             112.0
Minimum_Wage                             0.95
Official Language                      Arabic
oop_health_exp                           0.28
Physicians_per_1k                        1.72
Population                         43053054.0
Unemployment_Rate                        0.12
Name: DZ, dtype: object

We do not want to include Vatican City in our DataFrame due to their birthing process. Delete Vatican city from the dataframe.

In [ ]:
#delete Vatican City from the data
df_health.drop('VA')

,Country,Pop_Density,Land_Area,Birth_Rate,CO2_Emissions,CPI,Fertility_Rate,GDP,Infant mortality_per_1k,Life_Expectancy,Maternal_Mortality_per_100k,Minimum_Wage,Official Language,oop_health_exp,Physicians_per_1k,Population,Unemployment_Rate
Abbreviation,,,,,,,,,,,,,,,,,
AD,Andorra,164.0,468.0,7.20,469.0,NaN,1.27,3.154058e+09,2.7,NaN,NaN,6.63,Catalan,0.36,3.33,77142.0,NaN
AE,United Arab Emirates,118.0,83600.0,10.33,206324.0,114.52,1.41,4.211420e+11,6.5,77.8,3.0,NaN,Arabic,0.18,2.53,9770529.0,0.02
AF,Afghanistan,60.0,652230.0,32.49,8672.0,149.90,4.47,1.910135e+10,47.9,64.5,638.0,0.43,Pashto,0.78,0.28,38041754.0,0.11
AG,Antigua and Barbuda,223.0,443.0,15.33,557.0,113.81,1.99,1.727759e+09,5.0,76.9,42.0,3.04,English,0.24,2.76,97118.0,NaN
AL,Albania,105.0,28748.0,11.78,4536.0,119.05,1.62,1.527808e+10,7.8,78.5,15.0,1.12,Albanian,0.57,1.20,2854191.0,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WS,Samoa,70.0,2831.0,24.38,246.0,117.56,3.88,8.506550e+08,13.6,73.2,43.0,0.78,Samoan,0.12,0.34,202506.0,0.08
YE,Yemen,56.0,527968.0,30.45,10609.0,157.58,3.79,2.691440e+10,42.9,66.1,164.0,NaN,Arabic,0.81,0.31,29161922.0,0.13
ZA,South Africa,49.0,1219090.0,20.51,476644.0,158.93,2.41,3.514320e+11,28.5,63.9,119.0,NaN,Afrikaans,0.08,0.91,58558270.0,0.28
ZM,Zambia,25.0,752618.0,36.19,5141.0,212.31,4.63,2.306472e+10,40.4,63.5,213.0,0.24,English,0.28,1.19,17861030.0,0.11
ZW,Zimbabwe,38.0,390757.0,30.68,10983.0,105.51,3.62,2.144076e+10,33.9,61.2,458.0,NaN,Shona,0.26,0.21,14645468.0,0.05

In [ ]:
# what is the official language of the nation of the 186th row. Use 185 since Python starts at 0
df_health.iloc[185]
print(df_health['Official Language'].iloc[185])

Afrikaans

In [ ]:
#sort the dataframe by infant mortality rate.
df_health_copy= df_health.sort_values('Infant mortality_per_1k', ascending = False)
df_health_copy.head(10)

,Country,Pop_Density,Land_Area,Birth_Rate,CO2_Emissions,CPI,Fertility_Rate,GDP,Infant mortality_per_1k,Life_Expectancy,Maternal_Mortality_per_100k,Minimum_Wage,Official Language,oop_health_exp,Physicians_per_1k,Population,Unemployment_Rate
Abbreviation,,,,,,,,,,,,,,,,,
CF,Central African Republic,8.0,622984.0,35.35,297.0,186.86,4.72,2.220307e+09,84.5,52.8,829.0,0.37,French,0.40,0.06,4745185.0,0.04
SL,Sierra Leone,111.0,71740.0,33.41,1093.0,234.16,4.26,3.941474e+09,78.5,54.3,1120.0,0.57,English,0.38,0.03,7813215.0,0.04
SO,Somalia,25.0,637657.0,41.75,645.0,NaN,6.07,4.720727e+09,76.6,57.1,829.0,NaN,Arabic,NaN,0.02,15442905.0,0.11
NG,Nigeria,226.0,923768.0,37.91,120369.0,267.51,5.39,4.481200e+11,75.7,54.3,917.0,0.54,English,0.72,0.38,200963599.0,0.08
TD,Chad,13.0,1284000.0,42.17,1016.0,117.70,5.75,1.131495e+10,71.4,54.0,1140.0,0.60,French,0.56,0.04,15946876.0,0.02
CD,Democratic Republic of the Congo,40.0,2344858.0,41.18,2021.0,133.85,5.92,4.731962e+10,68.2,60.4,473.0,0.18,French,0.37,0.07,86790567.0,0.04
LS,Lesotho,71.0,30355.0,26.81,2512.0,155.86,3.14,2.460072e+09,65.7,53.7,544.0,0.41,English,0.17,0.07,2125268.0,0.23
GN,Guinea,53.0,245857.0,36.36,2996.0,262.95,4.70,1.359028e+10,64.9,61.2,576.0,NaN,French,0.55,0.08,12771246.0,0.04
SS,South Sudan,18.0,644329.0,35.01,1727.0,4583.71,4.70,1.199780e+10,63.7,57.6,1150.0,NaN,English,0.61,NaN,11062113.0,0.12
GQ,Equatorial Guinea,50.0,28051.0,33.24,5655.0,124.35,4.51,1.102677e+10,62.6,58.4,301.0,1.05,Spanish,0.72,0.40,1355986.0,0.06

In [ ]:
#create a new dataframe that includes all the columns, but only for countries whose offical language is Spanish
df_health_spanish= df_health[df_health['Official Language'] =='Spanish']
df_health_spanish.head()
df_health_spanish.shape

(19, 17)

In [ ]:
#what is the mean infant mortality per 1000 infants in countries whose offical language is spanish
round(df_health_spanish['Infant mortality_per_1k'].mean(),2)

np.float64(15.56)

In [ ]:
#what is the median maternal mortality in countries whose official language is spanish?
df_health_spanish['Maternal_Mortality_per_100k'].median()

65.0

In [ ]:
#create a new column for GDP per capita and find the nation with fourth highest GDP per capita. Divide GDP by Population size
df_health['GDP_per_capita'] = df_health['GDP']/df_health['Population']
#sort by gdp per capita
df_health_gdp_sort = df_health.sort_values('GDP_per_capita', ascending=False)
#df_health_gdp_sort.head()
#find the fourth country using index 3 because python starts at 0
fourth_country = df_health_gdp_sort.iloc[3]
print(fourth_country)
#print that country's maternal mortality rate
print(fourth_country['Maternal_Mortality_per_100k'])

Country                           Switzerland
Pop_Density                             219.0
Land_Area                             41277.0
Birth_Rate                               10.0
CO2_Emissions                         34477.0
CPI                                     99.55
Fertility_Rate                           1.52
GDP                            703082000000.0
Infant mortality_per_1k                   3.7
Life_Expectancy                          83.6
Maternal_Mortality_per_100k               5.0
Minimum_Wage                              NaN
Official Language                      German
oop_health_exp                           0.28
Physicians_per_1k                         4.3
Population                          8574832.0
Unemployment_Rate                        0.05
GDP_per_capita                   81993.676378
Name: CH, dtype: object
5.0

In [ ]:
#what is the average maternal mortality rate per 100k for all nations
round(df_health['Maternal_Mortality_per_100k'].mean(),2)

np.float64(160.39)

In [ ]:
#what percent of health care is paid out of pocket by country with the lowest infant mortaltiy
lowest_infant_mortality = df_health.sort_values('Infant mortality_per_1k').iloc[0]
print(lowest_infant_mortality)
print(lowest_infant_mortality['oop_health_exp'])

Country                               Finland
Pop_Density                              18.0
Land_Area                            338145.0
Birth_Rate                                8.6
CO2_Emissions                         45871.0
CPI                                    112.33
Fertility_Rate                           1.41
GDP                            268761000000.0
Infant mortality_per_1k                   1.4
Life_Expectancy                          81.7
Maternal_Mortality_per_100k               3.0
Minimum_Wage                              NaN
Official Language                     Swedish
oop_health_exp                            0.2
Physicians_per_1k                        3.81
Population                          5520314.0
Unemployment_Rate                        0.07
GDP_per_capita                    48685.81751
Name: FI, dtype: object
0.2

In [ ]:
#what perent of health care is paid out of pocket by the country with the highest infant mortality?
highest_infant_mortality = df_health.sort_values('Infant mortality_per_1k',ascending=False).iloc[0]
print(highest_infant_mortality)
print(highest_infant_mortality['oop_health_exp'])

Country                        Central African Republic
Pop_Density                                         8.0
Land_Area                                      622984.0
Birth_Rate                                        35.35
CO2_Emissions                                     297.0
CPI                                              186.86
Fertility_Rate                                     4.72
GDP                                        2220307369.0
Infant mortality_per_1k                            84.5
Life_Expectancy                                    52.8
Maternal_Mortality_per_100k                       829.0
Minimum_Wage                                       0.37
Official Language                                French
oop_health_exp                                      0.4
Physicians_per_1k                                  0.06
Population                                    4745185.0
Unemployment_Rate                                  0.04
GDP_per_capita                               467.907441
Name: CF, dtype: object
0.4